### PR TITLE
Refined mqtt connection on startup

### LINKED ISSUE #17: Refine MQTT connection on startup
MQTT topics contain Device ID and MQTT connection/subscription is established during startup.

In the case when device is started for the first time it obviously doesn't have an ID and subscribing will fail. It should be reattempted later.

### PR DESCRIPTION
**Pull request by villejuutila**
Resolves #17

### CODE REVIEW

File: lib/main.dart [hunk 1]
```diff
@@ -54,7 +54,11 @@ void _configureLogger({logLevel = Level.INFO}) {
 
 /// Setups MQTT Listeners
 void _setupMqttListeners() {
-  SurveysListener();
+  if (mqttClient.isConnected) {
+    SurveysListener();
+  } else {
+    logger.info("MQTT Client not connected, cannot setup listeners!");
```
Comment (kaeline) [inline lib/main.dart]: isn't this a warning level issue?

**Review by kaeline — APPROVED** [review]

File: lib/main.dart (hunk 1 above)
Comment (villejuutila) [reply lib/main.dart]: Resolved
